name: Deploy to Production!!!
on: 
  push:
    branches: 
      - main

jobs:
  create_tag:
    runs-on: ubuntu-latest
    outputs:
      output1: ${{ steps.previous_tag.outputs.tag_version }}
      output2: ${{ steps.tag.outputs.tag_version }}
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  
    steps:
      - name: checkout repo
        uses: actions/checkout@v4
        with:
          repository: ${{github.repository}}.wiki


      - name: generate the version number
        id: previous_tag
        run: |
            ls -al
            var=$(cat Home.textile | grep PRODUCTION | cut -d":" -f2 )
            echo $var
            echo "::set-output name=tag_version::$(echo ${var})"
     


      - name: get pull-request-label
        id: manual
        uses: actions-ecosystem/action-get-merged-pull-request@v0.0.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}

      - name: debug tag
        shell: bash
        run: |
           echo "${{ steps.previous_tag.outputs.tag_version }}"
      
      - name: create tag name
        id: tag
        shell: bash
        run: |
            echo "${{ steps.manual.outputs.labels }}"
            # tag=$(git describe --tags --abbrev=0 | sed 's/v//')
            version="${{ steps.manual.outputs.labels }}"
            echo "${{ steps.tag.outputs.tag_version }}"
            tag=$(echo ${{ steps.previous_tag.outputs.tag_version }} | sed 's/v//')
            IFS='.' read -r -a tag_array <<< "$tag"

            if [[ "${version}"  == "minor" ]]
            then
              temp=${tag_array[1]}
              ((temp=temp+1))
              echo "${temp}"
              null_value=0
              newTag="v${tag_array[0]}.${temp}.${null_value}"
              echo "latest-tag=v${tag_array[0]}.${temp}.${null_value}"  >> $GITHUB_ENV
              echo "::set-output name=tag_version::$(echo ${newTag})"
            elif [[ "${version}" == "major" ]]
            then
              temp=${tag_array[0]}
              ((temp=temp+1))
              echo "${temp}"
              newTag="v${temp}.${tag_array[1]}.${tag_array[2]}"
              echo "latest-tag=v${temp}.${tag_array[1]}.${tag_array[2]}" >> $GITHUB_ENV
              echo "::set-output name=tag_version::$(echo ${newTag})"
            else
              temp=${tag_array[2]}
              ((temp=temp+1))
              echo "${temp}"
              newTag="v${tag_array[0]}.${tag_array[1]}.${temp}"
              
              echo "latest-tag=v${tag_array[0]}.${tag_array[1]}.${temp}" >> $GITHUB_ENV
              echo "::set-output name=tag_version::$(echo ${newTag})"
            fi

            echo "New Tag: ${newTag}"

  create_release:
    needs: create_tag
    runs-on: ubuntu-latest
    outputs:
      output1: ${{needs.create_tag.outputs.output2}}
    steps: 
      - name: Checkout code
        uses: actions/checkout@master
      - name: Create Release
        id: create_release
        uses: actions/create-release@latest
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # This token is provided by Actions, you do not need to create your own token
        with:
          tag_name: ${{needs.create_tag.outputs.output2}}
          release_name: Production-${{needs.create_tag.outputs.output2}}
          draft: false
          prerelease: false

  deploy-production:
    runs-on: ubuntu-latest
    needs: create_release
    outputs:
      output1: ${{ needs.create_release.outputs.output1 }}
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.1
          bundler: 'latest'

      - name: debug
        run: |
            echo "${{ needs.create_release.outputs.output1 }}"

      - name: Set env variable
        env:
          SHOP_ACCESS_TOKEN: "PRODUCTION_ACCESS_TOKEN"
          SHOP_STORE: "PRODUCTION_STORE"
          SHOP_THEME_TOKEN: "PRODUCTION_THEME_TOKEN"
          SHOP_THEME_ID: "PRODUCTION_THEME_ID"
          SHOP_API_KEY: "PRODUCTION_API_KEY"
        # set job level env variable
        run: |
          echo "SHOP_ACCESS_TOKEN=${{ secrets[env.SHOP_ACCESS_TOKEN] }}" >> $GITHUB_ENV
          echo "SHOP_STORE=${{ secrets[env.SHOP_STORE] }}" >> $GITHUB_ENV
          echo "SHOP_THEME_ID=${{ secrets[env.SHOP_THEME_ID] }}" >> $GITHUB_ENV
          echo "SHOP_THEME_TOKEN=${{ secrets[env.SHOP_THEME_TOKEN] }}" >> $GITHUB_ENV
          echo "SHOP_API_KEY=${{ secrets[env.SHOP_API_KEY] }}" >> $GITHUB_ENV

      - name: Print env variable
        run: |
          echo "Store SHOP_STORE = $SHOP_STORE"

      - name: Install Shopify CLI
        run:  npm install & npm install -g @shopify/cli@3.57.1 @shopify/theme@3.57.1 laravel-mix@latest

      - name: Compile Tailwind files
        run: npm run production:tailwind
        
      - name: Deploy/Shopify Push
        run: shopify theme push --path src --store=$SHOP_STORE --theme $SHOP_THEME_ID --password $SHOP_THEME_TOKEN --allow-live
      
  push-version-wiki:
    runs-on: ubuntu-latest
    needs: deploy-production
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  
    steps:       
      - name: checkout repo
        uses: actions/checkout@v4
        with:
          repository: ${{github.repository}}.wiki

      - name: generate the version number
        run: |
            ls -al
            var=$(cat Home.textile | grep PRODUCTION | cut -d":" -f2)
            echo $var
            sed -i -e "s/$var/\ ${{needs.deploy-production.outputs.output1}}/g" Home.textile
            head -n 11 Home.textile > tmp.txt; mv tmp.txt Home.textile
            cat Home.textile
          
      - name: Commit files
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add .
          git commit -m "Add changes"
          git push


  create-pull-request_dev:
    runs-on: ubuntu-latest
    needs: push-version-wiki
    steps:

      - name: check out code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          ref: main

      - name: create a pull request on dev branch
        uses: devops-infra/action-pull-request@v0.4.2
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          source_branch: main
          target_branch: develop
          title: 'merging changes of US production back to develop branch'
          body: "**Automated pull request**"
          draft: false
          old_string: "<!-- Add your description here -->"
          new_string: "** Automatic pull request**"
          get_diff: true
          ignore_users: "dependabot"

  create-pull-request_release:
    runs-on: ubuntu-latest
    needs: push-version-wiki
    steps:

      - name: check out code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          ref: main

      - name: create a pull request on release branch
        uses: devops-infra/action-pull-request@v0.4.2
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          source_branch: main
          target_branch: release
          title: 'merging changes of US production back to US release branch'
          body: "**Automated pull request**"
          draft: false
          old_string: "<!-- Add your description here -->"
          new_string: "** Automatic pull request**"
          get_diff: true
          ignore_users: "dependabot"