name: Deploy to Production!!!
on:
  push:
    branches: 
      - main
      - demo-branch

jobs:
  create_tag:
    runs-on: ubuntu-latest
    outputs:
      output1: ${{ steps.previous_tag.outputs.tag_version }}
      output2: ${{ steps.tag.outputs.tag_version }}
    env:
      GITHUB_TOKEN: ${{ secrets.github_token }}  
    steps:
      - name: checkout repo
        uses: actions/checkout@v4
        with:
          repository: ${{github.repository}}.wiki
          ref: demo-branch

      # Rest of your steps remain unchanged
      
  # Create release job remains unchanged
  
  deploy-production:
    runs-on: ubuntu-latest
    needs: create_release
    outputs:
      output1: ${{ needs.create_release.outputs.output1 }}
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    steps:
      - uses: actions/checkout@v4
        with:
          ref: main
          
      # Rest of your steps remain unchanged

  push-version-wiki:
    runs-on: ubuntu-latest
    needs: deploy-production
    env:
      GITHUB_TOKEN: ${{ secrets.github_token }}  
    steps:       
      - name: checkout repo
        uses: actions/checkout@v4
        with:
          repository: ${{github.repository}}.wiki
          ref: main

      # Rest of your steps remain unchanged

  create-pull-request_dev:
    runs-on: ubuntu-latest
    needs: push-version-wiki
    steps:
      - name: check out code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          ref: demo-branch

      - name: create a pull request on dev branch
        uses: devops-infra/action-pull-request@v0.4.2
        with:
          GITHUB_TOKEN: ${{ secrets.github_token }}
          source_branch: demo-branch
          target_branch: develop
          title: 'merging changes of demo-branch to develop branch'
          body: "**Automated pull request**"
          draft: false

  create-pull-request_release:
    runs-on: ubuntu-latest
    needs: push-version-wiki
    steps:
      - name: check out code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          ref: demo-branch

      - name: create a pull request on release branch
        uses: devops-infra/action-pull-request@v0.4.2
        with:
          GITHUB_TOKEN: ${{ secrets.github_token }}
          source_branch: demo-branch
          target_branch: release
          title: 'merging changes of demo-branch to release branch'
          body: "**Automated pull request**"
          draft: false
