# This workflow is triggered on pushes to the Main Branch only.
on:
  push:
    branches:
      - main

jobs:
  build:
    name: Stencil Push and Script Manager Update
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v1

      - name: Set Node version to 14
        uses: actions/setup-node@v1
        with:
          node-version: 18.15.0

      - name: Install Dependencies
        run: |
          npm install -g @bigcommerce/stencil-cli
          npm install

      - name: Connect to store
        env:
          URL: ${{ secrets.STENCIL_STORE_URL }}
          TOKEN: ${{ secrets.STENCIL_TOKEN }}
        run: stencil init -u ${{ secrets.STENCIL_STORE_URL }} -t ${{ secrets.STENCIL_TOKEN }} -p 3000 -h https://api.bigcommerce.com

      - name: Push Theme
        run: |
          stencil push -d -a

      - name: Install Script Manager CLI
        run: |
          npm install -g @bigcommerce/storefront-data-hooks

      - name: Update Script in Script Manager
        env:
          STORE_HASH: ${{ secrets.STORE_HASH }}
          ACCESS_TOKEN: ${{ secrets.STENCIL_TOKEN }}
        run: |
          curl -X POST https://api.bigcommerce.com/stores/${{ secrets.STORE_HASH }}/v3/content/scripts \
          -H "X-Auth-Token: ${{ secrets.STENCIL_TOKEN }}" \
          -H "Content-Type: application/json" \
          -d '{
                "name": "Demo Script",
                "description": "Your Script Description",
                "html": "<script>alert("hii")</script>",
                "auto_uninstall": true,
                "load_method": "default",
                "location": "footer",
                "visibility": "all_pages"
              }'
