on:
  push:
    branches:
      - main

jobs:
  build:
    name: Stencil Push
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v1

      - name: Set Node version to 14
        uses: actions/setup-node@v1
        with:
          node-version: 18.15.0

      - name: Install Dependencies
        run: |
          npm install -g @bigcommerce/stencil-cli
          npm install

      - name: Connect to store
        env:
          URL: ${{ secrets.STENCIL_STORE_URL }}
          TOKEN: ${{ secrets.STENCIL_ACCESS_TOKEN }}
        run: stencil init -u ${{ secrets.STENCIL_STORE_URL }} -t ${{ secrets.STENCIL_ACCESS_TOKEN }} -p 3000 -h https://api.bigcommerce.com

      - name: Push Theme
        run: |
          stencil push -d -a

      - name: Create New Script in BigCommerce Store
        run: |
          cat << 'EOF' > create_script.js
          const fetch = require('node-fetch');

          let url = 'https://api.bigcommerce.com/stores/u3hrjyzyw3/v3/content/scripts';

          let options = {
            method: 'POST',
            headers: {
              Accept: 'application/json',
              'Content-Type': 'application/json',
              'X-Auth-Token': process.env.BC_API_TOKEN
            },
            body: JSON.stringify({
              name: "Bootstrap",
              description: "Build responsive websites",
              html: "",
              auto_uninstall: true,
              load_method: "default",
              location: "footer",
              visibility: "all_pages",
              kind: "script_tag",
              consent_category: "essential"
            })
          };

          fetch(url, options)
            .then(res => res.json())
            .then(json => console.log(json))
            .catch(err => console.error('error:' + err));
        env:
          BC_API_TOKEN: ${{ secrets.STENCIL_ACCESS_TOKEN }}
