# This workflow is triggered on pushes to the Main Branch only.
on:
  push:
    branches:
      - main

jobs:
  build:
    name: Stencil Push
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v1

      - name: Set Node version to 14
        uses: actions/setup-node@v1
        with:
          node-version: 18.15.0

      - name: Install Dependencies
        run: |
          npm install -g @bigcommerce/stencil-cli
          npm install

      - name: Create and Run Node.js Script
        env:
          STORE_HASH: ${{ secrets.STORE_HASH }}
          AUTH_TOKEN: ${{ secrets.AUTH_TOKEN }}
        run: |
          echo "const fetch = require('node-fetch'); \
          let url = \`https://api.bigcommerce.com/stores/${{ secrets.STORE_HASH }}/v3/content/scripts\`; \
          let options = { \
            method: 'POST', \
            headers: { \
              Accept: 'application/json', \
              'Content-Type': 'application/json', \
              'X-Auth-Token': ${{ secrets.AUTH_TOKEN }} \
            }, \
            body: JSON.stringify({ \
              name: 'Bootstrap', \
              description: 'Build responsive websites', \
              src: 'https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js', \
              auto_uninstall: true, \
              load_method: 'default', \
              location: 'footer', \
              visibility: 'all_pages', \
              kind: 'src', \
              consent_category: 'essential' \
            }) \
          }; \
          fetch(url, options) \
            .then(res => res.json()) \
            .then(json => console.log(json)) \
            .catch(err => console.error('error:' + err));" > add_script.js
          node add_script.js

      - name: Connect to store
        env:
          URL: ${{ secrets.STENCIL_STORE_URL }}
          TOKEN: ${{ secrets.STENCIL_STORE_TOKEN }}
        run: stencil init -u ${{ secrets.STENCIL_STORE_URL }} -t ${{ secrets.STENCIL_STORE_TOKEN }} -p 3000 -h https://api.bigcommerce.com

      - name: Push Theme
        run: |
          stencil push -d -a
