name: Create a pull request on main branch.

on:
  workflow_dispatch:
    inputs:
      title:
        required: true
      version:   
        description: 'Enter release version label'
        required: true
        type: choice
        options: 
          - patch
          - minor
          - major

jobs:
  create_pull_request:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: pull-request
        uses: repo-sync/pull-request@v2
        with:
          source_branch: "demo-branch"                                
          destination_branch: "main"                               
          pr_title: ${{ github.event.inputs.title }}               
          pr_label: ${{ github.event.inputs.version }}
          github_token: ${{ secrets.GITHUB_TOKEN }}

      - name: Save version type
        run: echo "${{ github.event.inputs.version }}" > .github/version_type.txt

      - name: Commit version type file
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
          git add .github/version_type.txt
          git commit -m "Add version type for release"

      - name: Push changes
        run: git push origin demo-branch
