name: Create a pull request on main branch

on:
  workflow_dispatch:
    inputs:
      title:
        description: 'Title of the pull request'
        required: true
        type: string
      version:
        description: 'Enter release version label'
        required: true
        type: choice
        options:
          - patch
          - minor
          - major

jobs:
  create_pull_request:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Create Pull Request
        uses: repo-sync/pull-request@v2
        with:
          source_branch: "demo-branch"
          destination_branch: "main"
          pr_title: ${{ github.event.inputs.title }}
          pr_label: ${{ github.event.inputs.version }}
          github_token: ${{ secrets.GITHUB_TOKEN }}
