name: Create Release

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    name: Create Release
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: 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
        with:
          tag_name: ${{ github.ref_name }}  # Use ref_name to get the tag name directly
          release_name: Release ${{ github.ref_name }}
          body: |
            Changes in this Release
            - First Change
            - Second Change
          draft: false
          prerelease: false
