name: Create Release

on:
  push:
    branches:
      - main

jobs:
  release:
    name: Create Release
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Git
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"

      - name: Get current version
        id: get_version
        run: |
          VERSION=$(git tag --sort=-v:refname | grep -E '^v[0-9]+\.[0-9]+\.[0-9]+' | head -n 1 | sed 's/^v//')
          if [ -z "$VERSION" ]; then
            VERSION="0.0.0"
          fi
          echo "::set-output name=version::$VERSION"

      - name: Increment version
        id: increment_version
        run: |
          VERSION=${{ steps.get_version.outputs.version }}
          IFS='.' read -r -a PARTS <<< "$VERSION"
          PATCH=$((PARTS[2] + 1))
          NEW_VERSION="${PARTS[0]}.${PARTS[1]}.$PATCH"
          echo "::set-output name=new_version::$NEW_VERSION"

      - name: Create new tag
        id: create_tag
        run: |
          NEW_TAG="v${{ steps.increment_version.outputs.new_version }}"
          echo "::set-output name=new_tag::$NEW_TAG"

      - name: Push new tag to GitHub
        env:
          GH_PAT: ${{ secrets.GH_PAT }}
        run: |
          NEW_TAG=${{ steps.create_tag.outputs.new_tag }}
          git tag -a $NEW_TAG -m "Release $NEW_TAG"
          git push https://$GH_PAT@github.com/${{ github.repository }} $NEW_TAG

      - name: Create GitHub release
        uses: actions/create-release@v1
        with:
          token: ${{ secrets.GH_PAT }}
          tag_name: $NEW_TAG
          release_name: Release $NEW_TAG
          body: |
            ## Changes in this release
            - Describe your changes here.
          draft: false
          prerelease: false
